name: DocFX Build and Publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build Documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docs_docfx/docfx.json
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: _site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
